---
- name: Manage Windows
  hosts: win
  become: false
  gather_facts: false
  tasks:
  - name: Copy file nagios installer  
    win_copy:
      src: ncpa-2.4.0.exe
      dest: C:\Temp\
  - name: Copy file nagios ps1   
    win_copy:
      src: inagios.ps1
      dest: C:\Temp\    
  - name: Install Nagios agent
    win_shell: C:\Temp\inagios.ps1 
    register: task_result  
  - name: Reboot immediately if there was a change.
    win_shell: |
      Start-Sleep -Seconds 5
      Restart-Computer -Force
    when: task_result is changed
  - name: Wait for the reboot to complete if there was a change.
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
    when: task_result is changed   
  
